@IsTest
public class MSAExternalSelectorTest {

  /*@IsTest
    private static void testGetData() {
        Test.startTest();
        //query
            final DataSource.QueryContext context = new DataSource.QueryContext();
            context.tableSelection = new DataSource.TableSelection();
            context.tableSelection.tableSelected = 'Health Plan Member';
            context.tableSelection.filter = new DataSource.Filter();
            context.tableSelection.filter.columnValue = '1-1244394134-52800958-1511388';
            MSAExternalSelector.getData(context);
            Test.stopTest();
        system.assertNotEquals(null,MSAExternalSelector.getData(context));
    } */
}